[project]
id = "kfiyugabaljsluayycye"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3004"
additional_redirect_urls = ["https://localhost:3004"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions]
send-welcome-email = {
  verify_jwt = false
}
